[package]
name = "fit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
flate2 = "1.0.30"
serde = {version = "1.0",features = ["derive"]}
serde_json = "1.0"
sha1 = "0.10"
